# Generated by Django 5.1.2 on 2025-10-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='profile_picture',
            field=models.ImageField(default='babysitters_profile_pics/default.jpg', upload_to='babysitters_profile_pics/'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='profile_picture',
            field=models.ImageField(default='parents_profile_pics/default.jpg', upload_to='parents_profile_pics/'),
        ),
    ]
