# Generated by Django 5.1.2 on 2025-10-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_babysitter_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
