# Generated by Django 5.1.2 on 2025-12-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_requests_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babysitter',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='meetings',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
