# Generated by Django 5.1.2 on 2026-01-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_babysitter_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kids',
            name='age',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
