# Generated by Django 5.1.2 on 2026-05-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_kids_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='is_ai_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetings',
            name='is_message_read_by_babysitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetings',
            name='is_message_read_by_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetings',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kids',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
