# Generated by Django 5.1.2 on 2026-05-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_meetings_is_ai_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
